# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Level_ACC',
            fields=[
                ('id', models.AutoField(primary_key=True, verbose_name='ID', auto_created=True, serialize=False)),
                ('level', models.DecimalField(decimal_places=3, max_digits=4, null=True)),
                ('redi_A', models.PositiveIntegerField(default=0)),
                ('redi_G', models.PositiveIntegerField(default=0)),
                ('hyper_A', models.PositiveIntegerField(default=0)),
                ('hyper_G', models.PositiveIntegerField(default=0)),
                ('sample', models.ForeignKey(to='web.Sample')),
                ('site', models.ForeignKey(to='web.Site')),
            ],
        ),
        migrations.CreateModel(
            name='Level_BLCA',
            fields=[
                ('id', models.AutoField(primary_key=True, verbose_name='ID', auto_created=True, serialize=False)),
                ('level', models.DecimalField(decimal_places=3, max_digits=4, null=True)),
                ('redi_A', models.PositiveIntegerField(default=0)),
                ('redi_G', models.PositiveIntegerField(default=0)),
                ('hyper_A', models.PositiveIntegerField(default=0)),
                ('hyper_G', models.PositiveIntegerField(default=0)),
                ('sample', models.ForeignKey(to='web.Sample')),
                ('site', models.ForeignKey(to='web.Site')),
            ],
        ),
        migrations.CreateModel(
            name='Level_BRCA',
            fields=[
                ('id', models.AutoField(primary_key=True, verbose_name='ID', auto_created=True, serialize=False)),
                ('level', models.DecimalField(decimal_places=3, max_digits=4, null=True)),
                ('redi_A', models.PositiveIntegerField(default=0)),
                ('redi_G', models.PositiveIntegerField(default=0)),
                ('hyper_A', models.PositiveIntegerField(default=0)),
                ('hyper_G', models.PositiveIntegerField(default=0)),
                ('sample', models.ForeignKey(to='web.Sample')),
                ('site', models.ForeignKey(to='web.Site')),
            ],
        ),
        migrations.CreateModel(
            name='Level_CESC',
            fields=[
                ('id', models.AutoField(primary_key=True, verbose_name='ID', auto_created=True, serialize=False)),
                ('level', models.DecimalField(decimal_places=3, max_digits=4, null=True)),
                ('redi_A', models.PositiveIntegerField(default=0)),
                ('redi_G', models.PositiveIntegerField(default=0)),
                ('hyper_A', models.PositiveIntegerField(default=0)),
                ('hyper_G', models.PositiveIntegerField(default=0)),
                ('sample', models.ForeignKey(to='web.Sample')),
                ('site', models.ForeignKey(to='web.Site')),
            ],
        ),
        migrations.CreateModel(
            name='Level_CHOL',
            fields=[
                ('id', models.AutoField(primary_key=True, verbose_name='ID', auto_created=True, serialize=False)),
                ('level', models.DecimalField(decimal_places=3, max_digits=4, null=True)),
                ('redi_A', models.PositiveIntegerField(default=0)),
                ('redi_G', models.PositiveIntegerField(default=0)),
                ('hyper_A', models.PositiveIntegerField(default=0)),
                ('hyper_G', models.PositiveIntegerField(default=0)),
                ('sample', models.ForeignKey(to='web.Sample')),
                ('site', models.ForeignKey(to='web.Site')),
            ],
        ),
        migrations.CreateModel(
            name='Level_COAD',
            fields=[
                ('id', models.AutoField(primary_key=True, verbose_name='ID', auto_created=True, serialize=False)),
                ('level', models.DecimalField(decimal_places=3, max_digits=4, null=True)),
                ('redi_A', models.PositiveIntegerField(default=0)),
                ('redi_G', models.PositiveIntegerField(default=0)),
                ('hyper_A', models.PositiveIntegerField(default=0)),
                ('hyper_G', models.PositiveIntegerField(default=0)),
                ('sample', models.ForeignKey(to='web.Sample')),
                ('site', models.ForeignKey(to='web.Site')),
            ],
        ),
        migrations.CreateModel(
            name='Level_DLBC',
            fields=[
                ('id', models.AutoField(primary_key=True, verbose_name='ID', auto_created=True, serialize=False)),
                ('level', models.DecimalField(decimal_places=3, max_digits=4, null=True)),
                ('redi_A', models.PositiveIntegerField(default=0)),
                ('redi_G', models.PositiveIntegerField(default=0)),
                ('hyper_A', models.PositiveIntegerField(default=0)),
                ('hyper_G', models.PositiveIntegerField(default=0)),
                ('sample', models.ForeignKey(to='web.Sample')),
                ('site', models.ForeignKey(to='web.Site')),
            ],
        ),
        migrations.CreateModel(
            name='Level_ESCA',
            fields=[
                ('id', models.AutoField(primary_key=True, verbose_name='ID', auto_created=True, serialize=False)),
                ('level', models.DecimalField(decimal_places=3, max_digits=4, null=True)),
                ('redi_A', models.PositiveIntegerField(default=0)),
                ('redi_G', models.PositiveIntegerField(default=0)),
                ('hyper_A', models.PositiveIntegerField(default=0)),
                ('hyper_G', models.PositiveIntegerField(default=0)),
                ('sample', models.ForeignKey(to='web.Sample')),
                ('site', models.ForeignKey(to='web.Site')),
            ],
        ),
        migrations.CreateModel(
            name='Level_GBM',
            fields=[
                ('id', models.AutoField(primary_key=True, verbose_name='ID', auto_created=True, serialize=False)),
                ('level', models.DecimalField(decimal_places=3, max_digits=4, null=True)),
                ('redi_A', models.PositiveIntegerField(default=0)),
                ('redi_G', models.PositiveIntegerField(default=0)),
                ('hyper_A', models.PositiveIntegerField(default=0)),
                ('hyper_G', models.PositiveIntegerField(default=0)),
                ('sample', models.ForeignKey(to='web.Sample')),
                ('site', models.ForeignKey(to='web.Site')),
            ],
        ),
        migrations.CreateModel(
            name='Level_HNSC',
            fields=[
                ('id', models.AutoField(primary_key=True, verbose_name='ID', auto_created=True, serialize=False)),
                ('level', models.DecimalField(decimal_places=3, max_digits=4, null=True)),
                ('redi_A', models.PositiveIntegerField(default=0)),
                ('redi_G', models.PositiveIntegerField(default=0)),
                ('hyper_A', models.PositiveIntegerField(default=0)),
                ('hyper_G', models.PositiveIntegerField(default=0)),
                ('sample', models.ForeignKey(to='web.Sample')),
                ('site', models.ForeignKey(to='web.Site')),
            ],
        ),
        migrations.CreateModel(
            name='Level_KICH',
            fields=[
                ('id', models.AutoField(primary_key=True, verbose_name='ID', auto_created=True, serialize=False)),
                ('level', models.DecimalField(decimal_places=3, max_digits=4, null=True)),
                ('redi_A', models.PositiveIntegerField(default=0)),
                ('redi_G', models.PositiveIntegerField(default=0)),
                ('hyper_A', models.PositiveIntegerField(default=0)),
                ('hyper_G', models.PositiveIntegerField(default=0)),
                ('sample', models.ForeignKey(to='web.Sample')),
                ('site', models.ForeignKey(to='web.Site')),
            ],
        ),
        migrations.CreateModel(
            name='Level_KIRC',
            fields=[
                ('id', models.AutoField(primary_key=True, verbose_name='ID', auto_created=True, serialize=False)),
                ('level', models.DecimalField(decimal_places=3, max_digits=4, null=True)),
                ('redi_A', models.PositiveIntegerField(default=0)),
                ('redi_G', models.PositiveIntegerField(default=0)),
                ('hyper_A', models.PositiveIntegerField(default=0)),
                ('hyper_G', models.PositiveIntegerField(default=0)),
                ('sample', models.ForeignKey(to='web.Sample')),
                ('site', models.ForeignKey(to='web.Site')),
            ],
        ),
        migrations.CreateModel(
            name='Level_KIRP',
            fields=[
                ('id', models.AutoField(primary_key=True, verbose_name='ID', auto_created=True, serialize=False)),
                ('level', models.DecimalField(decimal_places=3, max_digits=4, null=True)),
                ('redi_A', models.PositiveIntegerField(default=0)),
                ('redi_G', models.PositiveIntegerField(default=0)),
                ('hyper_A', models.PositiveIntegerField(default=0)),
                ('hyper_G', models.PositiveIntegerField(default=0)),
                ('sample', models.ForeignKey(to='web.Sample')),
                ('site', models.ForeignKey(to='web.Site')),
            ],
        ),
        migrations.CreateModel(
            name='Level_LGG',
            fields=[
                ('id', models.AutoField(primary_key=True, verbose_name='ID', auto_created=True, serialize=False)),
                ('level', models.DecimalField(decimal_places=3, max_digits=4, null=True)),
                ('redi_A', models.PositiveIntegerField(default=0)),
                ('redi_G', models.PositiveIntegerField(default=0)),
                ('hyper_A', models.PositiveIntegerField(default=0)),
                ('hyper_G', models.PositiveIntegerField(default=0)),
                ('sample', models.ForeignKey(to='web.Sample')),
                ('site', models.ForeignKey(to='web.Site')),
            ],
        ),
        migrations.CreateModel(
            name='Level_LIHC',
            fields=[
                ('id', models.AutoField(primary_key=True, verbose_name='ID', auto_created=True, serialize=False)),
                ('level', models.DecimalField(decimal_places=3, max_digits=4, null=True)),
                ('redi_A', models.PositiveIntegerField(default=0)),
                ('redi_G', models.PositiveIntegerField(default=0)),
                ('hyper_A', models.PositiveIntegerField(default=0)),
                ('hyper_G', models.PositiveIntegerField(default=0)),
                ('sample', models.ForeignKey(to='web.Sample')),
                ('site', models.ForeignKey(to='web.Site')),
            ],
        ),
        migrations.CreateModel(
            name='Level_LUAD',
            fields=[
                ('id', models.AutoField(primary_key=True, verbose_name='ID', auto_created=True, serialize=False)),
                ('level', models.DecimalField(decimal_places=3, max_digits=4, null=True)),
                ('redi_A', models.PositiveIntegerField(default=0)),
                ('redi_G', models.PositiveIntegerField(default=0)),
                ('hyper_A', models.PositiveIntegerField(default=0)),
                ('hyper_G', models.PositiveIntegerField(default=0)),
                ('sample', models.ForeignKey(to='web.Sample')),
                ('site', models.ForeignKey(to='web.Site')),
            ],
        ),
        migrations.CreateModel(
            name='Level_LUSC',
            fields=[
                ('id', models.AutoField(primary_key=True, verbose_name='ID', auto_created=True, serialize=False)),
                ('level', models.DecimalField(decimal_places=3, max_digits=4, null=True)),
                ('redi_A', models.PositiveIntegerField(default=0)),
                ('redi_G', models.PositiveIntegerField(default=0)),
                ('hyper_A', models.PositiveIntegerField(default=0)),
                ('hyper_G', models.PositiveIntegerField(default=0)),
                ('sample', models.ForeignKey(to='web.Sample')),
                ('site', models.ForeignKey(to='web.Site')),
            ],
        ),
        migrations.CreateModel(
            name='Level_MESO',
            fields=[
                ('id', models.AutoField(primary_key=True, verbose_name='ID', auto_created=True, serialize=False)),
                ('level', models.DecimalField(decimal_places=3, max_digits=4, null=True)),
                ('redi_A', models.PositiveIntegerField(default=0)),
                ('redi_G', models.PositiveIntegerField(default=0)),
                ('hyper_A', models.PositiveIntegerField(default=0)),
                ('hyper_G', models.PositiveIntegerField(default=0)),
                ('sample', models.ForeignKey(to='web.Sample')),
                ('site', models.ForeignKey(to='web.Site')),
            ],
        ),
        migrations.CreateModel(
            name='Level_OV',
            fields=[
                ('id', models.AutoField(primary_key=True, verbose_name='ID', auto_created=True, serialize=False)),
                ('level', models.DecimalField(decimal_places=3, max_digits=4, null=True)),
                ('redi_A', models.PositiveIntegerField(default=0)),
                ('redi_G', models.PositiveIntegerField(default=0)),
                ('hyper_A', models.PositiveIntegerField(default=0)),
                ('hyper_G', models.PositiveIntegerField(default=0)),
                ('sample', models.ForeignKey(to='web.Sample')),
                ('site', models.ForeignKey(to='web.Site')),
            ],
        ),
        migrations.CreateModel(
            name='Level_PAAD',
            fields=[
                ('id', models.AutoField(primary_key=True, verbose_name='ID', auto_created=True, serialize=False)),
                ('level', models.DecimalField(decimal_places=3, max_digits=4, null=True)),
                ('redi_A', models.PositiveIntegerField(default=0)),
                ('redi_G', models.PositiveIntegerField(default=0)),
                ('hyper_A', models.PositiveIntegerField(default=0)),
                ('hyper_G', models.PositiveIntegerField(default=0)),
                ('sample', models.ForeignKey(to='web.Sample')),
                ('site', models.ForeignKey(to='web.Site')),
            ],
        ),
        migrations.CreateModel(
            name='Level_PCPG',
            fields=[
                ('id', models.AutoField(primary_key=True, verbose_name='ID', auto_created=True, serialize=False)),
                ('level', models.DecimalField(decimal_places=3, max_digits=4, null=True)),
                ('redi_A', models.PositiveIntegerField(default=0)),
                ('redi_G', models.PositiveIntegerField(default=0)),
                ('hyper_A', models.PositiveIntegerField(default=0)),
                ('hyper_G', models.PositiveIntegerField(default=0)),
                ('sample', models.ForeignKey(to='web.Sample')),
                ('site', models.ForeignKey(to='web.Site')),
            ],
        ),
        migrations.CreateModel(
            name='Level_PRAD',
            fields=[
                ('id', models.AutoField(primary_key=True, verbose_name='ID', auto_created=True, serialize=False)),
                ('level', models.DecimalField(decimal_places=3, max_digits=4, null=True)),
                ('redi_A', models.PositiveIntegerField(default=0)),
                ('redi_G', models.PositiveIntegerField(default=0)),
                ('hyper_A', models.PositiveIntegerField(default=0)),
                ('hyper_G', models.PositiveIntegerField(default=0)),
                ('sample', models.ForeignKey(to='web.Sample')),
                ('site', models.ForeignKey(to='web.Site')),
            ],
        ),
        migrations.CreateModel(
            name='Level_READ',
            fields=[
                ('id', models.AutoField(primary_key=True, verbose_name='ID', auto_created=True, serialize=False)),
                ('level', models.DecimalField(decimal_places=3, max_digits=4, null=True)),
                ('redi_A', models.PositiveIntegerField(default=0)),
                ('redi_G', models.PositiveIntegerField(default=0)),
                ('hyper_A', models.PositiveIntegerField(default=0)),
                ('hyper_G', models.PositiveIntegerField(default=0)),
                ('sample', models.ForeignKey(to='web.Sample')),
                ('site', models.ForeignKey(to='web.Site')),
            ],
        ),
        migrations.CreateModel(
            name='Level_SARC',
            fields=[
                ('id', models.AutoField(primary_key=True, verbose_name='ID', auto_created=True, serialize=False)),
                ('level', models.DecimalField(decimal_places=3, max_digits=4, null=True)),
                ('redi_A', models.PositiveIntegerField(default=0)),
                ('redi_G', models.PositiveIntegerField(default=0)),
                ('hyper_A', models.PositiveIntegerField(default=0)),
                ('hyper_G', models.PositiveIntegerField(default=0)),
                ('sample', models.ForeignKey(to='web.Sample')),
                ('site', models.ForeignKey(to='web.Site')),
            ],
        ),
        migrations.CreateModel(
            name='Level_SKCM',
            fields=[
                ('id', models.AutoField(primary_key=True, verbose_name='ID', auto_created=True, serialize=False)),
                ('level', models.DecimalField(decimal_places=3, max_digits=4, null=True)),
                ('redi_A', models.PositiveIntegerField(default=0)),
                ('redi_G', models.PositiveIntegerField(default=0)),
                ('hyper_A', models.PositiveIntegerField(default=0)),
                ('hyper_G', models.PositiveIntegerField(default=0)),
                ('sample', models.ForeignKey(to='web.Sample')),
                ('site', models.ForeignKey(to='web.Site')),
            ],
        ),
        migrations.CreateModel(
            name='Level_STAD',
            fields=[
                ('id', models.AutoField(primary_key=True, verbose_name='ID', auto_created=True, serialize=False)),
                ('level', models.DecimalField(decimal_places=3, max_digits=4, null=True)),
                ('redi_A', models.PositiveIntegerField(default=0)),
                ('redi_G', models.PositiveIntegerField(default=0)),
                ('hyper_A', models.PositiveIntegerField(default=0)),
                ('hyper_G', models.PositiveIntegerField(default=0)),
                ('sample', models.ForeignKey(to='web.Sample')),
                ('site', models.ForeignKey(to='web.Site')),
            ],
        ),
        migrations.CreateModel(
            name='Level_TGCT',
            fields=[
                ('id', models.AutoField(primary_key=True, verbose_name='ID', auto_created=True, serialize=False)),
                ('level', models.DecimalField(decimal_places=3, max_digits=4, null=True)),
                ('redi_A', models.PositiveIntegerField(default=0)),
                ('redi_G', models.PositiveIntegerField(default=0)),
                ('hyper_A', models.PositiveIntegerField(default=0)),
                ('hyper_G', models.PositiveIntegerField(default=0)),
                ('sample', models.ForeignKey(to='web.Sample')),
                ('site', models.ForeignKey(to='web.Site')),
            ],
        ),
        migrations.CreateModel(
            name='Level_THCA',
            fields=[
                ('id', models.AutoField(primary_key=True, verbose_name='ID', auto_created=True, serialize=False)),
                ('level', models.DecimalField(decimal_places=3, max_digits=4, null=True)),
                ('redi_A', models.PositiveIntegerField(default=0)),
                ('redi_G', models.PositiveIntegerField(default=0)),
                ('hyper_A', models.PositiveIntegerField(default=0)),
                ('hyper_G', models.PositiveIntegerField(default=0)),
                ('sample', models.ForeignKey(to='web.Sample')),
                ('site', models.ForeignKey(to='web.Site')),
            ],
        ),
        migrations.CreateModel(
            name='Level_THYM',
            fields=[
                ('id', models.AutoField(primary_key=True, verbose_name='ID', auto_created=True, serialize=False)),
                ('level', models.DecimalField(decimal_places=3, max_digits=4, null=True)),
                ('redi_A', models.PositiveIntegerField(default=0)),
                ('redi_G', models.PositiveIntegerField(default=0)),
                ('hyper_A', models.PositiveIntegerField(default=0)),
                ('hyper_G', models.PositiveIntegerField(default=0)),
                ('sample', models.ForeignKey(to='web.Sample')),
                ('site', models.ForeignKey(to='web.Site')),
            ],
        ),
        migrations.CreateModel(
            name='Level_UCEC',
            fields=[
                ('id', models.AutoField(primary_key=True, verbose_name='ID', auto_created=True, serialize=False)),
                ('level', models.DecimalField(decimal_places=3, max_digits=4, null=True)),
                ('redi_A', models.PositiveIntegerField(default=0)),
                ('redi_G', models.PositiveIntegerField(default=0)),
                ('hyper_A', models.PositiveIntegerField(default=0)),
                ('hyper_G', models.PositiveIntegerField(default=0)),
                ('sample', models.ForeignKey(to='web.Sample')),
                ('site', models.ForeignKey(to='web.Site')),
            ],
        ),
        migrations.CreateModel(
            name='Level_UCS',
            fields=[
                ('id', models.AutoField(primary_key=True, verbose_name='ID', auto_created=True, serialize=False)),
                ('level', models.DecimalField(decimal_places=3, max_digits=4, null=True)),
                ('redi_A', models.PositiveIntegerField(default=0)),
                ('redi_G', models.PositiveIntegerField(default=0)),
                ('hyper_A', models.PositiveIntegerField(default=0)),
                ('hyper_G', models.PositiveIntegerField(default=0)),
                ('sample', models.ForeignKey(to='web.Sample')),
                ('site', models.ForeignKey(to='web.Site')),
            ],
        ),
        migrations.CreateModel(
            name='Level_UVM',
            fields=[
                ('id', models.AutoField(primary_key=True, verbose_name='ID', auto_created=True, serialize=False)),
                ('level', models.DecimalField(decimal_places=3, max_digits=4, null=True)),
                ('redi_A', models.PositiveIntegerField(default=0)),
                ('redi_G', models.PositiveIntegerField(default=0)),
                ('hyper_A', models.PositiveIntegerField(default=0)),
                ('hyper_G', models.PositiveIntegerField(default=0)),
                ('sample', models.ForeignKey(to='web.Sample')),
                ('site', models.ForeignKey(to='web.Site')),
            ],
        ),
        migrations.RemoveField(
            model_name='levellite',
            name='sample',
        ),
        migrations.RemoveField(
            model_name='levellite',
            name='site',
        ),
        migrations.DeleteModel(
            name='LevelLite',
        ),
    ]
