# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20180502_1538'),
    ]

    operations = [
        migrations.CreateModel(
            name='LevelLite',
            fields=[
                ('id', models.AutoField(auto_created=True, verbose_name='ID', primary_key=True, serialize=False)),
                ('level', models.DecimalField(decimal_places=3, null=True, max_digits=4)),
                ('redi_A', models.PositiveIntegerField(default=0)),
                ('redi_G', models.PositiveIntegerField(default=0)),
                ('hyper_A', models.PositiveIntegerField(default=0)),
                ('hyper_G', models.PositiveIntegerField(default=0)),
                ('sample', models.ForeignKey(to='web.Sample')),
                ('site', models.ForeignKey(to='web.Site')),
            ],
        ),
        migrations.RemoveField(
            model_name='level_acc',
            name='sample',
        ),
        migrations.RemoveField(
            model_name='level_acc',
            name='site',
        ),
        migrations.RemoveField(
            model_name='level_blca',
            name='sample',
        ),
        migrations.RemoveField(
            model_name='level_blca',
            name='site',
        ),
        migrations.RemoveField(
            model_name='level_brca',
            name='sample',
        ),
        migrations.RemoveField(
            model_name='level_brca',
            name='site',
        ),
        migrations.RemoveField(
            model_name='level_cesc',
            name='sample',
        ),
        migrations.RemoveField(
            model_name='level_cesc',
            name='site',
        ),
        migrations.RemoveField(
            model_name='level_chol',
            name='sample',
        ),
        migrations.RemoveField(
            model_name='level_chol',
            name='site',
        ),
        migrations.RemoveField(
            model_name='level_coad',
            name='sample',
        ),
        migrations.RemoveField(
            model_name='level_coad',
            name='site',
        ),
        migrations.RemoveField(
            model_name='level_dlbc',
            name='sample',
        ),
        migrations.RemoveField(
            model_name='level_dlbc',
            name='site',
        ),
        migrations.RemoveField(
            model_name='level_esca',
            name='sample',
        ),
        migrations.RemoveField(
            model_name='level_esca',
            name='site',
        ),
        migrations.RemoveField(
            model_name='level_gbm',
            name='sample',
        ),
        migrations.RemoveField(
            model_name='level_gbm',
            name='site',
        ),
        migrations.RemoveField(
            model_name='level_hnsc',
            name='sample',
        ),
        migrations.RemoveField(
            model_name='level_hnsc',
            name='site',
        ),
        migrations.RemoveField(
            model_name='level_kich',
            name='sample',
        ),
        migrations.RemoveField(
            model_name='level_kich',
            name='site',
        ),
        migrations.RemoveField(
            model_name='level_kirc',
            name='sample',
        ),
        migrations.RemoveField(
            model_name='level_kirc',
            name='site',
        ),
        migrations.RemoveField(
            model_name='level_kirp',
            name='sample',
        ),
        migrations.RemoveField(
            model_name='level_kirp',
            name='site',
        ),
        migrations.RemoveField(
            model_name='level_lgg',
            name='sample',
        ),
        migrations.RemoveField(
            model_name='level_lgg',
            name='site',
        ),
        migrations.RemoveField(
            model_name='level_lihc',
            name='sample',
        ),
        migrations.RemoveField(
            model_name='level_lihc',
            name='site',
        ),
        migrations.RemoveField(
            model_name='level_luad',
            name='sample',
        ),
        migrations.RemoveField(
            model_name='level_luad',
            name='site',
        ),
        migrations.RemoveField(
            model_name='level_lusc',
            name='sample',
        ),
        migrations.RemoveField(
            model_name='level_lusc',
            name='site',
        ),
        migrations.RemoveField(
            model_name='level_meso',
            name='sample',
        ),
        migrations.RemoveField(
            model_name='level_meso',
            name='site',
        ),
        migrations.RemoveField(
            model_name='level_ov',
            name='sample',
        ),
        migrations.RemoveField(
            model_name='level_ov',
            name='site',
        ),
        migrations.RemoveField(
            model_name='level_paad',
            name='sample',
        ),
        migrations.RemoveField(
            model_name='level_paad',
            name='site',
        ),
        migrations.RemoveField(
            model_name='level_pcpg',
            name='sample',
        ),
        migrations.RemoveField(
            model_name='level_pcpg',
            name='site',
        ),
        migrations.RemoveField(
            model_name='level_prad',
            name='sample',
        ),
        migrations.RemoveField(
            model_name='level_prad',
            name='site',
        ),
        migrations.RemoveField(
            model_name='level_read',
            name='sample',
        ),
        migrations.RemoveField(
            model_name='level_read',
            name='site',
        ),
        migrations.RemoveField(
            model_name='level_sarc',
            name='sample',
        ),
        migrations.RemoveField(
            model_name='level_sarc',
            name='site',
        ),
        migrations.RemoveField(
            model_name='level_skcm',
            name='sample',
        ),
        migrations.RemoveField(
            model_name='level_skcm',
            name='site',
        ),
        migrations.RemoveField(
            model_name='level_stad',
            name='sample',
        ),
        migrations.RemoveField(
            model_name='level_stad',
            name='site',
        ),
        migrations.RemoveField(
            model_name='level_tgct',
            name='sample',
        ),
        migrations.RemoveField(
            model_name='level_tgct',
            name='site',
        ),
        migrations.RemoveField(
            model_name='level_thca',
            name='sample',
        ),
        migrations.RemoveField(
            model_name='level_thca',
            name='site',
        ),
        migrations.RemoveField(
            model_name='level_thym',
            name='sample',
        ),
        migrations.RemoveField(
            model_name='level_thym',
            name='site',
        ),
        migrations.RemoveField(
            model_name='level_ucec',
            name='sample',
        ),
        migrations.RemoveField(
            model_name='level_ucec',
            name='site',
        ),
        migrations.RemoveField(
            model_name='level_ucs',
            name='sample',
        ),
        migrations.RemoveField(
            model_name='level_ucs',
            name='site',
        ),
        migrations.RemoveField(
            model_name='level_uvm',
            name='sample',
        ),
        migrations.RemoveField(
            model_name='level_uvm',
            name='site',
        ),
        migrations.DeleteModel(
            name='Level_ACC',
        ),
        migrations.DeleteModel(
            name='Level_BLCA',
        ),
        migrations.DeleteModel(
            name='Level_BRCA',
        ),
        migrations.DeleteModel(
            name='Level_CESC',
        ),
        migrations.DeleteModel(
            name='Level_CHOL',
        ),
        migrations.DeleteModel(
            name='Level_COAD',
        ),
        migrations.DeleteModel(
            name='Level_DLBC',
        ),
        migrations.DeleteModel(
            name='Level_ESCA',
        ),
        migrations.DeleteModel(
            name='Level_GBM',
        ),
        migrations.DeleteModel(
            name='Level_HNSC',
        ),
        migrations.DeleteModel(
            name='Level_KICH',
        ),
        migrations.DeleteModel(
            name='Level_KIRC',
        ),
        migrations.DeleteModel(
            name='Level_KIRP',
        ),
        migrations.DeleteModel(
            name='Level_LGG',
        ),
        migrations.DeleteModel(
            name='Level_LIHC',
        ),
        migrations.DeleteModel(
            name='Level_LUAD',
        ),
        migrations.DeleteModel(
            name='Level_LUSC',
        ),
        migrations.DeleteModel(
            name='Level_MESO',
        ),
        migrations.DeleteModel(
            name='Level_OV',
        ),
        migrations.DeleteModel(
            name='Level_PAAD',
        ),
        migrations.DeleteModel(
            name='Level_PCPG',
        ),
        migrations.DeleteModel(
            name='Level_PRAD',
        ),
        migrations.DeleteModel(
            name='Level_READ',
        ),
        migrations.DeleteModel(
            name='Level_SARC',
        ),
        migrations.DeleteModel(
            name='Level_SKCM',
        ),
        migrations.DeleteModel(
            name='Level_STAD',
        ),
        migrations.DeleteModel(
            name='Level_TGCT',
        ),
        migrations.DeleteModel(
            name='Level_THCA',
        ),
        migrations.DeleteModel(
            name='Level_THYM',
        ),
        migrations.DeleteModel(
            name='Level_UCEC',
        ),
        migrations.DeleteModel(
            name='Level_UCS',
        ),
        migrations.DeleteModel(
            name='Level_UVM',
        ),
    ]
